source 'https://rubygems.org'

# Enhanced IRB
gem 'pry'

# 이쁘게 찍자
gem 'awesome_print'

# 주식정보 받아오기
gem 'stock_quote'

# 환율 변환용 은행
gem 'eu_central_bank'

# 날씨 gem
gem 'forecast_io'

#위도,경도 변환 gem
gem 'geocoder'

# Artii
gem 'artii'
